### ISSUE TITLE
where can i get the bag file

### ISSUE THREAD

**Issue by jack-wolfs** [leonzz/argus-autoronto#8]
it looks good, but i can't run it because i could not find the bag file, could you tell me where can i get it?

**Comment by leonzz** [comment]
@jack-wolfs thanks for the interest. Since this project was built for [aUToronto](https://www.autodrive.utoronto.ca/), the rosbag comes from real data collected during their test. Maybe worth contacting @keenan-burnett for possibility of sharing bag files.

**Comment by keenan-burnett** [comment]
@leonzz which rosbags do we need to share?
If it's only 1-2, I can make them publicly available.

**Comment by leonzz** [comment]
@keenan-burnett `_2018-12-02-12-48-40_m1_tests.bag` is the most commonly used one for our testing for planned path and obstacles.
`_2019-01-18-15-19-31_public_roads.bag` is the one we used to show better map as it's on public road.

**Comment by keenan-burnett** [comment]
I've added publicly available google drive links to those two rosbags.

**Comment by leonzz** [comment]
Thanks Keenan-) @jack-wolfs refer to the updated README file for rosbags download links
